[package]
name = "rust-challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
tempfile = "3.8.1"
thiserror = "1.0.50"
