name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@v2
      with: 
        tool: nextest,cargo-llvm-cov
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo nextest run
    - name: Coverage
      run: cargo llvm-cov
